== Project setup

=== Create the project directory

[source,bash]
----
mkdir angular2-example
cd angular2-example
git init .
----

=== Spring Boot app using start.spring.io

Ensure you are in the top-level project directory 'angular2-example'.

Run the following, which will use https://start.spring.io to generate a starter project.

[source,bash]
----
curl https://start.spring.io/starter.zip \
  -d type=maven-project \
  -d applicationName="AngularApplication" \
  -d packageName="jp.bikon" \
  -d groupId="jp.bikon" -d name="Angular 2 Application" -d artifactId="angular2-example" \
  -d description="Angular 2 Application" \
  -d dependencies=web,actuator \
  -d version="0.1.0-SNAPSHOT" \
  -d javaVersion="1.8" \
  | tar -xzvf -
----

=== Use YAML for project configuration

Spring Boot is able to use http://yaml.org[YAML], or the older style properties files for configuration. This project will use YAML.

[source,bash]
----
mv src/main/resources/application.properties src/main/resources/application.yml
----

=== Add Spring Boot files to git

Run the following:

[source,bash]
----
git add .
git commit -m 'Spring Boot app using start.spring.io'
----

=== Test with 'spring-boot:run'

Run the following (using http://maven.apache.org[Maven]), and browse to http://localhost:8080

[source,bash]
----
mvn spring-boot:run
----

It is also possible to setup a Spring Boot project using https://gradle.org[Gradle]

If using Gradle, use the following command to start the Spring Boot app:

[source,bash]
----
./gradlew bootRun
----

=== Angular 2 app using angular-cli

Initialise an Angular 2 application, with the additional options to use http://sass-lang.com[Sass].

It is also possible to create a new Angular 2 project using 'ng new angular2-example', although in this example we are adding Angular to an existing application.

[source,bash]
----
ng init --style=scss
----

Choose 'n' when prompted to overwrite the existing .gitignore.

Note: It is also possible to change the CSS preprocessor after the app was created:

[source,bash]
----
ng set defaults.styleExt scss
----

=== Add Angular files to git

The 'node_modules' created by Angular will be excluded from version control.

Run the following:

[source,bash]
----
# Amend .gitignore
echo '' >> .gitignore
echo '### Angular2 ###' >> .gitignore
echo 'node_modules' >> .gitignore

# Add the files
git add .
git commit -m 'Angular 2 app using angular-cli'
----

=== Test with 'ng serve'

Run the following, and browse to http://localhost:4200

[source,bash]
----
ng serve
----

=== Integrate Angular 2 with Spring Boot

The Angular 2 'dist' directory will be amended to use the default Spring location for static files.

The enables us to develop the front-end using the default 'ng serve', and deploy the application using 'spring-boot:run'.

Amend angular-cli.json and change the location of the 'dist' directory.

.angular-cli.json
[source,json]
----
...
"outDir": "src/main/resources/static/",
...
----

==== Test the integration

Run the following command to build the app and deploy using Spring.

[source,bash]
----
ng build
mvn spring-boot:run
----

Open http://localhost:8080[http://localhost:8080]

